### ISSUE TITLE
生活鯖の紹介を追加

### ISSUE THREAD

**Issue by Kamesuta** [Numa-Lab/www.numalab.net#7]
ここに生活鯖の紹介を追加したい。  
あともう少し別の場所にも追加してもいいかも。

![image](https://user-images.githubusercontent.com/16362824/150676802-5ce4d460-0015-4e02-8eb4-a595ac06d639.png)

**Comment by Zect3279** [comment]
それっぽいアイコンと説明文を PR: #12 で追加しました
![image](https://user-images.githubusercontent.com/57027411/150926509-092a9b47-a15c-4845-a4d4-093910a8592d.png)
